version: '3.8'

services:

  atn:
    container_name: atn
    image: node:21.7.1-alpine3.18
    volumes:
      - ./app:/app
      - node-cache:/usr/local/share/.cache
    working_dir: /app
    ports:
      - "3000:3000"
#    command: "npm run start:dev"

volumes:
  node-cache:
